wandb_version: 1

backbone:
  value: resnet18
coreset_sampling_ratio:
  value: 0.05
eval_batch_size:
  value: 16
layers:
  value:
  - layer3
  - layer4
model:
  value: PatchCore
num_neighbors:
  value: 9
num_workers:
  value: 0
train_batch_size:
  value: 16
training_dir:
  value: /Users/zideng/Work/Anomaly/data/black_widows_200
